insert into competition (comp_designation, comp_opponent, team_id, games) values ('Greece', 'Prickly Bog Sedge', 7, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Portugal', 'Dacite Manzanita', 11, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Bahia', 6, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Philippines', 'Heartleaf Twistflower', 5, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Pakistan', 'Gold Coast Jasmine', 17, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Indonesia', 'Tolmie''s Penstemon', 5, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Mexico', 'Smallanthus', 11, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Uganda', 'Tulare Gooseberry', 13, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Kazakhstan', 'Arabian Coffee', 19, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Uzbekistan', 'Sobralia', 12, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Malta', 'Othake', 13, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Greece', 'Gray Globemallow', 15, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Palmer''s Monkeyflower', 2, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('France', 'Orange Lichen', 2, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Sticky Monkeyflower', 9, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Russia', 'Shrubby Lespedeza', 3, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Tajikistan', 'Glandular False Calico', 3, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Yellow Prickle', 17, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Fewflower Meadow-rue', 15, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Hoffmann''s Buckwheat', 18, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Luxembourg', 'Longbeard Mariposa Lily', 6, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Jackfruit', 17, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Serbia', 'Oahu False Ohelo', 5, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Croatia', 'Sticky Cinquefoil', 3, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Indonesia', 'Alliaria', 2, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Belarus', 'Peters'' Blackthread Lichen', 13, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Canada', 'Brachythecium Moss', 17, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Cracked Lichen', 19, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('New Zealand', 'Lodgepole Lupine', 10, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Philippines', 'Dicranum Moss', 7, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Thailand', 'Isopterygium Moss', 20, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Russia', 'Klamath Erigeron', 10, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Narrowleaf Bedstraw', 15, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('China', 'Hammitt''s Claycress', 6, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Japan', 'Broom', 6, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Brazil', 'Thinleaf Alder', 3, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Brazil', 'Neoparrya', 19, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Vietnam', 'Tepary Bean', 11, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Philippines', 'Boxelder', 1, 10);
insert into competition (comp_designation, comp_opponent, team_id, games) values ('Croatia', 'Utah Agave', 3, 10);
