insert into team (team_name, captain) values ('Magpie, black-backed', 230);
insert into team (team_name, captain) values ('Beaver, american', 63);
insert into team (team_name, captain) values ('Langur, gray', 92);
insert into team (team_name, captain) values ('Grenadier, purple', 153);
insert into team (team_name, captain) values ('Swan, black', 100);
insert into team (team_name, captain) values ('Hartebeest, red', 129);
insert into team (team_name, captain) values ('Sidewinder', 80);
insert into team (team_name, captain) values ('Baboon, chacma', 66);
insert into team (team_name, captain) values ('Arctic hare', 2);
insert into team (team_name, captain) values ('Flicker, field', 92);
insert into team (team_name, captain) values ('Phascogale, brush-tailed', 161);
insert into team (team_name, captain) values ('Monkey, rhesus', 201);
insert into team (team_name, captain) values ('Parakeet, rose-ringed', 85);
insert into team (team_name, captain) values ('Great kiskadee', 41);
insert into team (team_name, captain) values ('Black-tailed deer', 101);
insert into team (team_name, captain) values ('Grenadier, purple', 144);
insert into team (team_name, captain) values ('Squirrel, indian giant', 207);
insert into team (team_name, captain) values ('Levaillant''s barbet', 70);
insert into team (team_name, captain) values ('Wild water buffalo', 163);
insert into team (team_name, captain) values ('Lion, steller''s sea', 156);
